### ISSUE TITLE
Change Compilesdk version to 33

### ISSUE THREAD

**Issue by siju-s** [siju-s/AceExplorer#3]
**Acceptance** criteria:
1. Build is successful and able to install on Android 13, Android 12 and below

**Comment by sourabhchouhan07** [comment]
I want to work on this issue ,please assign it to me @siju-s

**Comment by siju-s** [comment]
Assigned !

**Comment by Vedant755** [comment]
Hey, can I contribute to the issue? Have a great knowledge about it!
